### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by Pilvinen** [starandserpent/Weltschmerz#6]
There might be an issue with memory usage.

1) It seems empty space might be taking up memory. This can be seen when the world size is set to too large so that the computer running it will eventually run out of memory. But instead of consistently running out of memory after a certain number of chunks has been generated **smaller** worlds can achieve a _higher chunk count, which is counter intuitive.

I am not certain whether this is Weltschmerz or Terra issue. I'm suspecting Weltschmerz so I'm opening the ticket under Weltschmerz for now.

2) When generating terrain before any terrain is generated, but the world is up and running the memory usage climbs up steadily to around 3.5 GB. After that terrain starts appearing and taking up more memory in increments of maybe 40 MB. 

3) After a sort of "section" has been generated the world generation takes a pause, maybe 5-10 seconds. During this time no new terrain is being generated. When the generation resumes a chunk of maybe 400 MB of memory is reserved for something. After that new terrain starts appearing eating memory again in chunks of around 40 MB.

![https://i.snag.gy/XRh08F.jpg](https://i.snag.gy/XRh08F.jpg)

This is the shape of the area after which the terrain generation takes a small break catching it's breath for reasons unknown.

**Comment by Pawlost** [comment]
This is terra bug, Weltschmerz should take around 100 MB of constant memory
