### ISSUE TITLE
Set generation height (ocean level)

### ISSUE THREAD

**Issue by Pilvinen** [starandserpent/Weltschmerz#7]
Currently terrain gets generated based on the load marker radius, but the only way to generate a flat surface terrain is to limit Y generation level at the max radius.

This results in terrain which is generated really high and you have to fly high up to the terrain to interact with it. This is getting increasingly annoying.

To fix the issue we should add support for setting the "ocean level" or surface generation height.

In other words terrain generation should not be influenced by the load marker. Instead the load marker should load terrain when terrain is encountered in the world.

Ultimately the goal is of course that the load marker follows the player and we load and unload terrain based on a bunch of rules.

But as far as Weltschmerz is concerned we should have support for setting the surface generation level which is not dependent on the location of the load marker. Instead the load marker and camera should be placed at the surface generation level.

**Comment by Pawlost** [comment]
Support for this is planned. It is one of the base enhancment for generating this https://github.com/starandserpent/Weltschmerz/issues/2 in terra

**Comment by Pawlost** [comment]
Terrain hight is configurable
